
services:
  mysql:
    image: mysql:8.0
    container_name: crm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2904
      MYSQL_DATABASE: crm
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - crm_network


volumes:
  mysql_data:

networks:
  crm_network: 